# Generated by Django 4.0.4 on 2022-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profile',
            field=models.CharField(default='comming soon', max_length=300),
        ),
    ]
