# Generated by Django 4.0.4 on 2022-06-22 13:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='ユーザーがこの管理サイトにログインできるかどうかを指定します。'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
