# Generated by Django 4.0.4 on 2022-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
